__version__ = "1.10.0"

__version_name__ = __version__

try:
    from du.VersionMeta import versionName, buildTime

    # Dynamic meta
    versionMeta = versionName + "@" + buildTime

    __version_name__ += " [%s]" % versionMeta if versionMeta else ""

except ImportError:
    # Not generated by package.sh
    pass
